import streamlit as st
import pandas as pd
from sqlalchemy import create_engine
import os
from dotenv import load_dotenv
from fpdf import FPDF
from datetime import datetime

# ==========================================
# 1. PAGE CONFIGURATION & DISCORD THEMING
# ==========================================
st.set_page_config(
    page_title="Aegis | Discord Admin UI", 
    page_icon="🤖", 
    layout="wide", 
    initial_sidebar_state="expanded"
)

# Injecting Custom HTML/CSS/Bootstrap for a polished Discord-style frontend
st.markdown("""
    <style>
        /* Discord Dark Theme Backgrounds */
        .stApp { background-color: #36393f; color: #dcddde; }
        
        /* Discord Metric Cards */
        .discord-card {
            background-color: #2f3136;
            border-left: 5px solid #5865F2; /* Discord Blurple */
            border-radius: 8px;
            padding: 20px;
            margin-bottom: 15px;
            box-shadow: 0 4px 6px rgba(0,0,0,0.3);
        }
        .discord-label { font-size: 0.9rem; color: #8e9297; text-transform: uppercase; font-weight: bold; }
        .discord-value { font-size: 2.2rem; color: #ffffff; font-weight: 800; margin-top: 5px; }
        
        /* Headers and Typography */
        h1, h2, h3 { font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif !important; }
        .main-header { color: #ffffff !important; font-weight: 800; border-bottom: 2px solid #5865F2; padding-bottom: 10px;}
        .sub-header { color: #5865F2 !important; margin-top: 20px; }
        
        /* Sidebar and Export Box */
        .css-1d391kg { background-color: #202225 !important; }
        .export-box { background-color: #2f3136; padding: 15px; border-radius: 8px; border: 1px dashed #5865F2; }
    </style>
""", unsafe_allow_html=True)

# ==========================================
# 2. THE "WOW" FEATURE: ACADEMIC PDF EXPORT
# ==========================================
class AcademicReport(FPDF):
    def header(self):
        self.set_font("Times", "B", 12)
        self.set_text_color(88, 101, 242) # Discord Blurple
        self.cell(0, 10, "AEGIS DISCORD MODERATION SYSTEM - ACADEMIC COMPLIANCE REPORT", align="C")
        self.ln(15)

    def footer(self):
        self.set_y(-15)
        self.set_font("Times", "I", 8)
        self.set_text_color(128, 128, 128)
        self.cell(0, 10, f"Page {self.page_no()} | Generated by Aegis Bot Platform", align="C")

def generate_academic_pdf(df_msgs, df_usrs):
    """Dynamically generates a downloadable PDF report of server metrics."""
    pdf = AcademicReport()
    pdf.add_page()
    
    # Title Section
    pdf.set_font("Times", "B", 18)
    pdf.set_text_color(0, 0, 0)
    pdf.cell(0, 10, "Monthly Discord Server Health & NLP Toxicity Audit", ln=True)
    pdf.set_font("Times", "I", 11)
    pdf.cell(0, 10, f"Reporting Period: {datetime.now().strftime('%B %Y')}", ln=True)
    pdf.ln(5)
    
    # Executive Summary
    pdf.set_font("Times", "B", 14)
    pdf.cell(0, 10, "1. Executive Server Metrics", ln=True)
    pdf.set_font("Times", "", 12)
    
    total_msgs = len(df_msgs)
    avg_tox = df_msgs['toxicity_score'].mean() if total_msgs > 0 else 0
    
    summary = (
        f"During this monitoring cycle, the Aegis NLP Engine parsed {total_msgs} active Discord messages. "
        f"The server's baseline toxicity moving average is currently evaluated at {avg_tox:.4f}. "
        f"Statistical anomalies tracking above the 0.60 threshold have been successfully mitigated."
    )
    pdf.multi_cell(0, 8, summary)
    pdf.ln(10)
    
    # Top Offenders
    pdf.set_font("Times", "B", 14)
    pdf.cell(0, 10, "2. Top Offenders Leaderboard (Highest Risk Profiles)", ln=True)
    pdf.set_font("Times", "B", 11)
    
    # Table Header
    pdf.set_fill_color(220, 220, 220)
    pdf.cell(95, 8, "Discord User ID", border=1, fill=True)
    pdf.cell(95, 8, "Trust Score (Lower = Higher Risk)", border=1, fill=True, ln=True)
    
    # Table Data
    pdf.set_font("Times", "", 11)
    top_offenders = df_usrs.sort_values(by='trust_score', ascending=True).head(10)
    for _, row in top_offenders.iterrows():
        pdf.cell(95, 8, str(row['user_id']), border=1)
        pdf.cell(95, 8, f"{row['trust_score']:.2f}", border=1, ln=True)
        
    return bytes(pdf.output())

# ==========================================
# 3. LIVE POSTGRESQL DATABASE INTEGRATION
# ==========================================
load_dotenv()
DATABASE_URL = os.getenv("SUPABASE_URL", "postgresql+psycopg2://postgres:qpDt2IqS9mbjgBgD@db.spibrcrelsmdfvpurnac.supabase.co:5432/postgres")

if "postgresql://" in DATABASE_URL:
    DATABASE_URL = DATABASE_URL.replace("postgresql://", "postgresql+psycopg2://")

@st.cache_resource
def get_db_connection():
    return create_engine(DATABASE_URL)

engine = get_db_connection()

try:
    df_messages = pd.read_sql("SELECT * FROM messages", engine)
    df_users = pd.read_sql("SELECT * FROM users", engine)
except Exception as e:
    st.error(f"Database Connection Error: {e}")
    st.stop()

# ==========================================
# 4. DASHBOARD UI RENDERING
# ==========================================

st.markdown("<h1 class='main-header'>🤖 Aegis Discord Administrator UI</h1>", unsafe_allow_html=True)
st.markdown("Real-time PostgreSQL telemetry and Statistical Process Control for Discord server health.")

# SIDEBAR: The Wow Feature (PDF Export)
with st.sidebar:
    st.markdown("<h2>🛠️ Admin Tools</h2>", unsafe_allow_html=True)
    st.markdown("<div class='export-box'>", unsafe_allow_html=True)
    st.write("**Automated PDF Reporting**")
    st.write("Generate academic-grade compliance reports of server health and offenders.")
    
    if not df_messages.empty and not df_users.empty:
        pdf_bytes = generate_academic_pdf(df_messages, df_users)
        st.download_button(
            label="📥 Export Monthly Report (PDF)",
            data=pdf_bytes,
            file_name=f"Aegis_Discord_Report_{datetime.now().strftime('%Y-%m-%d')}.pdf",
            mime="application/pdf",
            use_container_width=True
        )
    else:
        st.warning("Awaiting database records to generate report.")
    st.markdown("</div>", unsafe_allow_html=True)

# MAIN CONTENT
if df_messages.empty:
    st.info("📡 Database is currently empty. Go send some messages in your Discord Server!")
else:
    df_messages['timestamp'] = pd.to_datetime(df_messages['timestamp'])
    
    # 1. Top Metrics Grid
    c1, c2, c3 = st.columns(3)
    with c1:
        st.markdown(f"<div class='discord-card'><div class='discord-label'>Messages Scanned</div><div class='discord-value'>{len(df_messages):,}</div></div>", unsafe_allow_html=True)
    with c2:
        st.markdown(f"<div class='discord-card'><div class='discord-label'>Global Avg Toxicity</div><div class='discord-value'>{df_messages['toxicity_score'].mean():.4f}</div></div>", unsafe_allow_html=True)
    with c3:
        st.markdown(f"<div class='discord-card'><div class='discord-label'>Spikes Mitigated</div><div class='discord-value'>{len(df_messages[df_messages['toxicity_score'] >= 0.60])}</div></div>", unsafe_allow_html=True)

    # 2. Server Health Timeline (Line Chart)
    st.markdown("<h3 class='sub-header'>📈 Live Server Health Timeline (Toxicity Spikes)</h3>", unsafe_allow_html=True)
    chart_data = df_messages[['timestamp', 'toxicity_score']].set_index('timestamp').sort_index()
    st.line_chart(chart_data, color="#5865F2") # Discord Blurple line

# 3. Tables Row
    col_left, col_right = st.columns(2)
    
    with col_left:
        st.markdown("<h3 class='sub-header'>⚠️ Top Offenders Leaderboard</h3>", unsafe_allow_html=True)
        # Sort by lowest trust score
        leaderboard = df_users[['user_id', 'trust_score']].sort_values(by='trust_score', ascending=True).reset_index(drop=True)
        leaderboard.columns = ['Discord User ID', 'Current Trust Score']
        st.dataframe(leaderboard.style.format({"Current Trust Score": "{:.2f}"}), use_container_width=True, height=300)
        
    with col_right:  # <--- THIS IS THE FIXED LINE
        st.markdown("<h3 class='sub-header'>📝 Live Message Intercepts</h3>", unsafe_allow_html=True)
        recent_logs = df_messages[['timestamp', 'content', 'toxicity_score']].sort_values(by='timestamp', ascending=False).reset_index(drop=True)
        recent_logs.columns = ['Time', 'Message Content', 'Toxicity']
        st.dataframe(recent_logs.style.format({"Toxicity": "{:.4f}"}), use_container_width=True, height=300)
